-- ──────────────────────────────────────────────────────────────
-- DOT Field — Flyway Migration V1: Authentication Schema
-- Compatible with both existing databases (PostgreSQL) and blank databases (H2 dev mode).
-- ──────────────────────────────────────────────────────────────

-- 1. Create users table
CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(255) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    role VARCHAR(50) NOT NULL DEFAULT 'USER',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

-- 2. Ensure profiles table exists (for fresh databases)
CREATE TABLE IF NOT EXISTS profiles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL,
    phone VARCHAR(255),
    location VARCHAR(255),
    linkedin_url VARCHAR(255),
    github_url VARCHAR(255),
    portfolio_url VARCHAR(255),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

-- 3. Add user_id column to profiles table
ALTER TABLE profiles ADD COLUMN IF NOT EXISTS user_id BIGINT;

-- 4. Add UNIQUE index on profiles.user_id
CREATE UNIQUE INDEX IF NOT EXISTS uk_profiles_user_id ON profiles(user_id);
