-- ──────────────────────────────────────────────────────────────
-- DOT Field — Flyway Migration V1: Complete Baseline Schema
-- Creates ALL application tables from scratch.
-- ──────────────────────────────────────────────────────────────

-- ┌──────────────────────────────────────────────────────────┐
-- │ 1. users (standalone — referenced by profiles in V2)     │
-- └──────────────────────────────────────────────────────────┘
CREATE TABLE users (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email          VARCHAR(255)  NOT NULL UNIQUE,
    password_hash  VARCHAR(255)  NOT NULL,
    role           VARCHAR(50)   NOT NULL DEFAULT 'USER',
    created_at     TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at     TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- ┌──────────────────────────────────────────────────────────┐
-- │ 2. profiles (standalone initially; user_id added in V2)  │
-- └──────────────────────────────────────────────────────────┘
CREATE TABLE profiles (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name           VARCHAR(255)  NOT NULL,
    email          VARCHAR(255)  NOT NULL,
    phone          VARCHAR(255),
    location       VARCHAR(255),
    linkedin_url   VARCHAR(255),
    github_url     VARCHAR(255),
    portfolio_url  VARCHAR(255),
    created_at     TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at     TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- ┌──────────────────────────────────────────────────────────┐
-- │ 3. skills (FK → profiles)                                │
-- └──────────────────────────────────────────────────────────┘
CREATE TABLE skills (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    profile_id  BIGINT        NOT NULL,
    name        VARCHAR(255)  NOT NULL,
    category    VARCHAR(255)  NOT NULL,

    CONSTRAINT fk_skills_profile_id
        FOREIGN KEY (profile_id) REFERENCES profiles(id)
);

-- ┌──────────────────────────────────────────────────────────┐
-- │ 4. experiences (FK → profiles)                           │
-- └──────────────────────────────────────────────────────────┘
CREATE TABLE experiences (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    profile_id  BIGINT          NOT NULL,
    company     VARCHAR(255)    NOT NULL,
    role        VARCHAR(255)    NOT NULL,
    description VARCHAR(2000),
    start_date  DATE,
    end_date    DATE,

    CONSTRAINT fk_experiences_profile_id
        FOREIGN KEY (profile_id) REFERENCES profiles(id)
);

-- ┌──────────────────────────────────────────────────────────┐
-- │ 5. educations (FK → profiles)                            │
-- └──────────────────────────────────────────────────────────┘
CREATE TABLE educations (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    profile_id      BIGINT        NOT NULL,
    institution     VARCHAR(255)  NOT NULL,
    degree          VARCHAR(255)  NOT NULL,
    field_of_study  VARCHAR(255),
    start_date      DATE,
    end_date        DATE,
    grade           VARCHAR(255),

    CONSTRAINT fk_educations_profile_id
        FOREIGN KEY (profile_id) REFERENCES profiles(id)
);

-- ┌──────────────────────────────────────────────────────────┐
-- │ 6. projects (FK → profiles)                              │
-- └──────────────────────────────────────────────────────────┘
CREATE TABLE projects (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    profile_id  BIGINT          NOT NULL,
    name        VARCHAR(255)    NOT NULL,
    description VARCHAR(2000),
    github_url  VARCHAR(255),
    live_url    VARCHAR(255),

    CONSTRAINT fk_projects_profile_id
        FOREIGN KEY (profile_id) REFERENCES profiles(id)
);

-- ┌──────────────────────────────────────────────────────────┐
-- │ 7. project_technologies (@ElementCollection on Project)  │
-- └──────────────────────────────────────────────────────────┘
CREATE TABLE project_technologies (
    project_id  BIGINT        NOT NULL,
    technology  VARCHAR(255),

    CONSTRAINT fk_project_technologies_project_id
        FOREIGN KEY (project_id) REFERENCES projects(id)
);

-- ┌──────────────────────────────────────────────────────────┐
-- │ 8. jobs (global — no user FK)                            │
-- └──────────────────────────────────────────────────────────┘
CREATE TABLE jobs (
    id                         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    external_id                VARCHAR(200),
    title                      VARCHAR(200)    NOT NULL,
    company                    VARCHAR(200)    NOT NULL,
    location                   VARCHAR(200),
    description                TEXT,
    job_url                    VARCHAR(2048),
    canonical_url              VARCHAR(2048),
    deduplication_fingerprint  VARCHAR(64),
    source                     VARCHAR(100)    NOT NULL,
    employment_type            VARCHAR(255),
    remote_type                VARCHAR(255),
    status                     VARCHAR(255)    NOT NULL,
    salary_min                 DECIMAL(15, 2),
    salary_max                 DECIMAL(15, 2),
    currency                   VARCHAR(10),
    posted_date                DATE,
    last_discovered_at         TIMESTAMP,
    created_at                 TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at                 TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT uk_jobs_source_external_id
        UNIQUE (source, external_id),
    CONSTRAINT uk_jobs_canonical_url
        UNIQUE (canonical_url)
);

CREATE INDEX idx_jobs_fingerprint ON jobs(deduplication_fingerprint);
