-- ──────────────────────────────────────────────────────────────
-- DOT Field — Flyway Migration V1: Authentication Schema
-- ──────────────────────────────────────────────────────────────

-- 1. Create users table
CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(255) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    role VARCHAR(50) NOT NULL DEFAULT 'USER',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- 2. Add user_id to profiles table (nullable initially for safe migration)
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.columns 
        WHERE table_name = 'profiles' AND column_name = 'user_id'
    ) THEN
        ALTER TABLE profiles ADD COLUMN user_id BIGINT;
    END IF;
END $$;

-- 3. Data-safe migration for existing profiles:
-- For any existing profile without a user_id, associate with an existing user matching email
-- or auto-create a user record so existing candidate profiles are preserved.
DO $$
DECLARE
    prof_record RECORD;
    new_user_id BIGINT;
BEGIN
    FOR prof_record IN SELECT id, email FROM profiles WHERE user_id IS NULL LOOP
        SELECT id INTO new_user_id FROM users WHERE LOWER(email) = LOWER(prof_record.email);
        
        IF new_user_id IS NULL THEN
            INSERT INTO users (email, password_hash, role, created_at, updated_at)
            VALUES (LOWER(prof_record.email), '$2a$10$MIGRATE_ONLY_LOCKED_ACCOUNT_PLACEHOLDER_HASH', 'USER', NOW(), NOW())
            RETURNING id INTO new_user_id;
        END IF;

        UPDATE profiles SET user_id = new_user_id WHERE id = prof_record.id;
    END LOOP;
END $$;

-- 4. Apply UNIQUE and FOREIGN KEY constraints on profiles.user_id
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.table_constraints 
        WHERE constraint_name = 'uk_profiles_user_id'
    ) THEN
        ALTER TABLE profiles ADD CONSTRAINT uk_profiles_user_id UNIQUE (user_id);
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM information_schema.table_constraints 
        WHERE constraint_name = 'fk_profiles_user'
    ) THEN
        ALTER TABLE profiles ADD CONSTRAINT fk_profiles_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE;
    END IF;
END $$;
