-- ──────────────────────────────────────────────────────────────
-- DOT Field — Flyway Migration V3: Application Tracking Domain
-- ──────────────────────────────────────────────────────────────

CREATE TABLE applications (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    profile_id       BIGINT        NOT NULL,
    job_id           BIGINT        NOT NULL,
    status           VARCHAR(50)   NOT NULL DEFAULT 'SAVED',
    notes            VARCHAR(2000),
    applied_at       TIMESTAMP,
    created_at       TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at       TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_applications_profile_id
        FOREIGN KEY (profile_id) REFERENCES profiles(id),
    CONSTRAINT fk_applications_job_id
        FOREIGN KEY (job_id) REFERENCES jobs(id),
    CONSTRAINT uk_applications_profile_job
        UNIQUE (profile_id, job_id)
);

CREATE INDEX idx_applications_profile_status ON applications(profile_id, status);
